apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redash.fullname" . }}-ui-extras
  labels:
    {{- include "redash.labels" . | nindent 4 }}
data:
  {{- .Values.server.uiExtras | toYaml | nindent 2 }}
